### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by grahamperrin** [bgpat/anchor-selector#2]
https://addons.mozilla.org/addon/anchor-selector/versions/?page=1#version-0.1

> Works with Firefox 48.0 and later 

However it seems to _not_ work with Waterfox 56.2.3. 

Do you need to correct the details at AMO?

**Comment by bgpat** [comment]
I've checked this extension requires Firefox 59 at least and fixed the details. Thanks for your report!

**Comment by grahamperrin** [comment]
Hi

https://addons.mozilla.org/addon/anchor-selector/versions/?page=1#version-0.1.2

> Works with Firefox for Android 48.0 and later, Firefox 48.0 and later 

– and the extension can be added to Waterfox 56.2.3 but again, it's not effective.

**Comment by bgpat** [comment]
Thanks! Fixed it.

**Comment by grahamperrin** [comment]
Thanks :+1: 

In addition you might like to add a `strict_min_version` as exemplified at https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/manifest.json#Example

Related: https://discourse.mozilla.org/t/-/32672?u=grahamperrin
