### ISSUE TITLE
Support "invisible" zero-sized anchors

### ISSUE THREAD

**Issue by thecodewarrior** [bgpat/anchor-selector#803]
Some pages may have empty elements that are used as anchors, and because they have zero size it's impossible to highlight them with this extension. For example this page:

https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html#DDB-PutItem-request-Item

The item headings themselves don't have IDs, but there are zero-sized anchors that do: 
![image](https://user-images.githubusercontent.com/5467669/194627117-78306478-b3ae-441f-b255-b114dc1df352.png)

Using the [Display #Anchors](https://addons.mozilla.org/en-US/firefox/addon/display-_anchors/) extension, you can see the anchors: 
![image](https://user-images.githubusercontent.com/5467669/194626906-e93a011f-c65e-44a5-85c8-d38c9246b4a8.png)

I'm not sure what the best solution to this would be, but your extension certainly is more polished than Display #Anchors, so it would be great if you supported this. Honestly I think taking a note from Display #Anchors and adding indicators (maybe just a `#`) next to every ID'd element would be great for usability in the first place, since you could see at a glance where your possibilities are instead of having to hunt around the page blindly.

Also it would be great if you added the github repository to the Firefox extension page. A closed-source extension asking for full site permissions is a bit uncomfortable. I only found this repo by downloading the extension, opening it up, and noticing the repo mentioned in the embedded readme file.

**Comment by bgpat** [comment]
Thank you for your feedback. This feature is supported in [v0.8.7](https://github.com/bgpat/anchor-selector/releases/tag/v0.8.7).
